name: Draw Keymap
on:
  workflow_dispatch:
  push:
    paths:
      - non/existing/path
      # - "config/**"
      # - .github/workflows/draw.yml
      # - keymap_drawer.config.yaml

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@v0.22.1
    permissions:
      contents: write
    with:
      keymap_patterns: config/boards/shields/eyeslash_corne/*.keymap
      commit_message: "[Draw] ${{ github.event.head_commit.message }}"
      destination: "commit"
      fail_on_error: ${{ fromJSON(true) }}
